os: linux

sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install hacking autopep8

script:
  - flake8
  - autopep8 -r . --diff | tee check_autopep8
  - test ! -s check_autopep8
